---
abstract: 'Filter plugin adapter for Text::Pipe'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Filter-Pipe
provides:
  Template::Plugin::Filter::Pipe:
    file: lib/Template/Plugin/Filter/Pipe.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Template: 0
  Template::Plugin::Filter: 0
  Test::Differences: 0
  Test::More: 0.88
  Text::Pipe: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Filter-Pipe
  homepage: http://search.cpan.org/dist/Template-Plugin-Filter-Pipe/
  repository: http://github.com/hanekomu/Template-Plugin-Filter-Pipe
version: 1.100860
